// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/proto/playlist.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistId string  `protobuf:"bytes,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
	PageToken  *string `protobuf:"bytes,2,opt,name=pageToken,proto3,oneof" json:"pageToken,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *GetRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type PageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalResults   uint32 `protobuf:"varint,1,opt,name=totalResults,proto3" json:"totalResults,omitempty"`
	ResultsPerPage uint32 `protobuf:"varint,2,opt,name=resultsPerPage,proto3" json:"resultsPerPage,omitempty"`
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{1}
}

func (x *PageInfo) GetTotalResults() uint32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *PageInfo) GetResultsPerPage() uint32 {
	if x != nil {
		return x.ResultsPerPage
	}
	return 0
}

type GetResponse1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind          string    `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Etag          string    `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	NextPageToken *string   `protobuf:"bytes,3,opt,name=nextPageToken,proto3,oneof" json:"nextPageToken,omitempty"`
	PrevPageToken *string   `protobuf:"bytes,4,opt,name=prevPageToken,proto3,oneof" json:"prevPageToken,omitempty"`
	PageInfo      *PageInfo `protobuf:"bytes,5,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
}

func (x *GetResponse1) Reset() {
	*x = GetResponse1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse1) ProtoMessage() {}

func (x *GetResponse1) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse1.ProtoReflect.Descriptor instead.
func (*GetResponse1) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse1) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetResponse1) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetResponse1) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

func (x *GetResponse1) GetPrevPageToken() string {
	if x != nil && x.PrevPageToken != nil {
		return *x.PrevPageToken
	}
	return ""
}

func (x *GetResponse1) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind          string                `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Etag          string                `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	NextPageToken *string               `protobuf:"bytes,3,opt,name=nextPageToken,proto3,oneof" json:"nextPageToken,omitempty"`
	PrevPageToken *string               `protobuf:"bytes,4,opt,name=prevPageToken,proto3,oneof" json:"prevPageToken,omitempty"`
	Items         []*GetResponse_Items  `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	PageInfo      *GetResponse_Pageinfo `protobuf:"bytes,6,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

func (x *GetResponse) GetPrevPageToken() string {
	if x != nil && x.PrevPageToken != nil {
		return *x.PrevPageToken
	}
	return ""
}

func (x *GetResponse) GetItems() []*GetResponse_Items {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetResponse) GetPageInfo() *GetResponse_Pageinfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetResponse_Default struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width  uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetResponse_Default) Reset() {
	*x = GetResponse_Default{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Default) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Default) ProtoMessage() {}

func (x *GetResponse_Default) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Default.ProtoReflect.Descriptor instead.
func (*GetResponse_Default) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetResponse_Default) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetResponse_Default) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetResponse_Default) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetResponse_Medium struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width  uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetResponse_Medium) Reset() {
	*x = GetResponse_Medium{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Medium) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Medium) ProtoMessage() {}

func (x *GetResponse_Medium) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Medium.ProtoReflect.Descriptor instead.
func (*GetResponse_Medium) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetResponse_Medium) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetResponse_Medium) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetResponse_Medium) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetResponse_High struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width  uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetResponse_High) Reset() {
	*x = GetResponse_High{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_High) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_High) ProtoMessage() {}

func (x *GetResponse_High) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_High.ProtoReflect.Descriptor instead.
func (*GetResponse_High) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 2}
}

func (x *GetResponse_High) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetResponse_High) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetResponse_High) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetResponse_Standard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width  uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetResponse_Standard) Reset() {
	*x = GetResponse_Standard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Standard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Standard) ProtoMessage() {}

func (x *GetResponse_Standard) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Standard.ProtoReflect.Descriptor instead.
func (*GetResponse_Standard) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 3}
}

func (x *GetResponse_Standard) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetResponse_Standard) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetResponse_Standard) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetResponse_Maxres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width  uint32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetResponse_Maxres) Reset() {
	*x = GetResponse_Maxres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Maxres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Maxres) ProtoMessage() {}

func (x *GetResponse_Maxres) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Maxres.ProtoReflect.Descriptor instead.
func (*GetResponse_Maxres) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 4}
}

func (x *GetResponse_Maxres) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetResponse_Maxres) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetResponse_Maxres) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetResponse_Thumbnails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default  *GetResponse_Default  `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Medium   *GetResponse_Medium   `protobuf:"bytes,2,opt,name=medium,proto3" json:"medium,omitempty"`
	High     *GetResponse_High     `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	Standard *GetResponse_Standard `protobuf:"bytes,4,opt,name=standard,proto3" json:"standard,omitempty"`
	Maxres   *GetResponse_Maxres   `protobuf:"bytes,5,opt,name=maxres,proto3" json:"maxres,omitempty"`
}

func (x *GetResponse_Thumbnails) Reset() {
	*x = GetResponse_Thumbnails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Thumbnails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Thumbnails) ProtoMessage() {}

func (x *GetResponse_Thumbnails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Thumbnails.ProtoReflect.Descriptor instead.
func (*GetResponse_Thumbnails) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 5}
}

func (x *GetResponse_Thumbnails) GetDefault() *GetResponse_Default {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *GetResponse_Thumbnails) GetMedium() *GetResponse_Medium {
	if x != nil {
		return x.Medium
	}
	return nil
}

func (x *GetResponse_Thumbnails) GetHigh() *GetResponse_High {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *GetResponse_Thumbnails) GetStandard() *GetResponse_Standard {
	if x != nil {
		return x.Standard
	}
	return nil
}

func (x *GetResponse_Thumbnails) GetMaxres() *GetResponse_Maxres {
	if x != nil {
		return x.Maxres
	}
	return nil
}

type GetResponse_Resourceid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	VideoId string `protobuf:"bytes,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
}

func (x *GetResponse_Resourceid) Reset() {
	*x = GetResponse_Resourceid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Resourceid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Resourceid) ProtoMessage() {}

func (x *GetResponse_Resourceid) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Resourceid.ProtoReflect.Descriptor instead.
func (*GetResponse_Resourceid) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 6}
}

func (x *GetResponse_Resourceid) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetResponse_Resourceid) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetResponse_Snippet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublishedAt            string                  `protobuf:"bytes,1,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	ChannelId              string                  `protobuf:"bytes,2,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Title                  string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnails             *GetResponse_Thumbnails `protobuf:"bytes,5,opt,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	ChannelTitle           string                  `protobuf:"bytes,6,opt,name=channelTitle,proto3" json:"channelTitle,omitempty"`
	PlaylistId             string                  `protobuf:"bytes,7,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
	Position               uint32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	ResourceId             *GetResponse_Resourceid `protobuf:"bytes,9,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	VideoOwnerChannelTitle string                  `protobuf:"bytes,10,opt,name=videoOwnerChannelTitle,proto3" json:"videoOwnerChannelTitle,omitempty"`
	VideoOwnerChannelId    string                  `protobuf:"bytes,11,opt,name=videoOwnerChannelId,proto3" json:"videoOwnerChannelId,omitempty"`
}

func (x *GetResponse_Snippet) Reset() {
	*x = GetResponse_Snippet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Snippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Snippet) ProtoMessage() {}

func (x *GetResponse_Snippet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Snippet.ProtoReflect.Descriptor instead.
func (*GetResponse_Snippet) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 7}
}

func (x *GetResponse_Snippet) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *GetResponse_Snippet) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetResponse_Snippet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetResponse_Snippet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetResponse_Snippet) GetThumbnails() *GetResponse_Thumbnails {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

func (x *GetResponse_Snippet) GetChannelTitle() string {
	if x != nil {
		return x.ChannelTitle
	}
	return ""
}

func (x *GetResponse_Snippet) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *GetResponse_Snippet) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *GetResponse_Snippet) GetResourceId() *GetResponse_Resourceid {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

func (x *GetResponse_Snippet) GetVideoOwnerChannelTitle() string {
	if x != nil {
		return x.VideoOwnerChannelTitle
	}
	return ""
}

func (x *GetResponse_Snippet) GetVideoOwnerChannelId() string {
	if x != nil {
		return x.VideoOwnerChannelId
	}
	return ""
}

type GetResponse_Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string               `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Etag    string               `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	Id      string               `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Snippet *GetResponse_Snippet `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
}

func (x *GetResponse_Items) Reset() {
	*x = GetResponse_Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Items) ProtoMessage() {}

func (x *GetResponse_Items) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Items.ProtoReflect.Descriptor instead.
func (*GetResponse_Items) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 8}
}

func (x *GetResponse_Items) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetResponse_Items) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetResponse_Items) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResponse_Items) GetSnippet() *GetResponse_Snippet {
	if x != nil {
		return x.Snippet
	}
	return nil
}

type GetResponse_Pageinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalResults   uint32 `protobuf:"varint,1,opt,name=totalResults,proto3" json:"totalResults,omitempty"`
	ResultsPerPage uint32 `protobuf:"varint,2,opt,name=resultsPerPage,proto3" json:"resultsPerPage,omitempty"`
}

func (x *GetResponse_Pageinfo) Reset() {
	*x = GetResponse_Pageinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_playlist_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse_Pageinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse_Pageinfo) ProtoMessage() {}

func (x *GetResponse_Pageinfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_playlist_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse_Pageinfo.ProtoReflect.Descriptor instead.
func (*GetResponse_Pageinfo) Descriptor() ([]byte, []int) {
	return file_api_proto_playlist_proto_rawDescGZIP(), []int{3, 9}
}

func (x *GetResponse_Pageinfo) GetTotalResults() uint32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *GetResponse_Pageinfo) GetResultsPerPage() uint32 {
	if x != nil {
		return x.ResultsPerPage
	}
	return 0
}

var File_api_proto_playlist_proto protoreflect.FileDescriptor

var file_api_proto_playlist_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22,
	0x5d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x56,
	0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x26,
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x50,
	0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x22, 0xdb, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x65,
	0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x74, 0x61, 0x67, 0x12,
	0x29, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0d, 0x70, 0x72,
	0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xdf, 0x0c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x74, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x74, 0x61, 0x67, 0x12, 0x29, 0x0a, 0x0d,
	0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x50,
	0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x35, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x49, 0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x1a, 0x48, 0x0a, 0x06, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x46, 0x0a, 0x04,
	0x48, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x1a, 0x4a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x1a, 0x48, 0x0a, 0x06, 0x4d, 0x61, 0x78, 0x72, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x84, 0x02, 0x0a, 0x0a, 0x54,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2f, 0x0a,
	0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x29,
	0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48,
	0x69, 0x67, 0x68, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64,
	0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4d, 0x61, 0x78, 0x72, 0x65, 0x73, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x72, 0x65,
	0x73, 0x1a, 0x3a, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x1a, 0xc5, 0x03,
	0x0a, 0x07, 0x53, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x3b, 0x0a, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b,
	0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x69, 0x64, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x16, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x13, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x1a, 0x73, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x65, 0x74, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x6e, 0x69, 0x70, 0x70, 0x65,
	0x74, 0x52, 0x07, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x1a, 0x56, 0x0a, 0x08, 0x50, 0x61,
	0x67, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x50, 0x65, 0x72, 0x50, 0x61,
	0x67, 0x65, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x50, 0x61, 0x67,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x36, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_proto_playlist_proto_rawDescOnce sync.Once
	file_api_proto_playlist_proto_rawDescData = file_api_proto_playlist_proto_rawDesc
)

func file_api_proto_playlist_proto_rawDescGZIP() []byte {
	file_api_proto_playlist_proto_rawDescOnce.Do(func() {
		file_api_proto_playlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_playlist_proto_rawDescData)
	})
	return file_api_proto_playlist_proto_rawDescData
}

var file_api_proto_playlist_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_playlist_proto_goTypes = []interface{}{
	(*GetRequest)(nil),             // 0: api.GetRequest
	(*PageInfo)(nil),               // 1: api.PageInfo
	(*GetResponse1)(nil),           // 2: api.GetResponse1
	(*GetResponse)(nil),            // 3: api.GetResponse
	(*GetResponse_Default)(nil),    // 4: api.GetResponse.Default
	(*GetResponse_Medium)(nil),     // 5: api.GetResponse.Medium
	(*GetResponse_High)(nil),       // 6: api.GetResponse.High
	(*GetResponse_Standard)(nil),   // 7: api.GetResponse.Standard
	(*GetResponse_Maxres)(nil),     // 8: api.GetResponse.Maxres
	(*GetResponse_Thumbnails)(nil), // 9: api.GetResponse.Thumbnails
	(*GetResponse_Resourceid)(nil), // 10: api.GetResponse.Resourceid
	(*GetResponse_Snippet)(nil),    // 11: api.GetResponse.Snippet
	(*GetResponse_Items)(nil),      // 12: api.GetResponse.Items
	(*GetResponse_Pageinfo)(nil),   // 13: api.GetResponse.Pageinfo
}
var file_api_proto_playlist_proto_depIdxs = []int32{
	1,  // 0: api.GetResponse1.pageInfo:type_name -> api.PageInfo
	12, // 1: api.GetResponse.items:type_name -> api.GetResponse.Items
	13, // 2: api.GetResponse.pageInfo:type_name -> api.GetResponse.Pageinfo
	4,  // 3: api.GetResponse.Thumbnails.default:type_name -> api.GetResponse.Default
	5,  // 4: api.GetResponse.Thumbnails.medium:type_name -> api.GetResponse.Medium
	6,  // 5: api.GetResponse.Thumbnails.high:type_name -> api.GetResponse.High
	7,  // 6: api.GetResponse.Thumbnails.standard:type_name -> api.GetResponse.Standard
	8,  // 7: api.GetResponse.Thumbnails.maxres:type_name -> api.GetResponse.Maxres
	9,  // 8: api.GetResponse.Snippet.thumbnails:type_name -> api.GetResponse.Thumbnails
	10, // 9: api.GetResponse.Snippet.resourceId:type_name -> api.GetResponse.Resourceid
	11, // 10: api.GetResponse.Items.snippet:type_name -> api.GetResponse.Snippet
	0,  // 11: api.Playlist.Get:input_type -> api.GetRequest
	3,  // 12: api.Playlist.Get:output_type -> api.GetResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_playlist_proto_init() }
func file_api_proto_playlist_proto_init() {
	if File_api_proto_playlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_playlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Default); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Medium); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_High); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Standard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Maxres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Thumbnails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Resourceid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Snippet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_playlist_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse_Pageinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_playlist_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_api_proto_playlist_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_proto_playlist_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_playlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_playlist_proto_goTypes,
		DependencyIndexes: file_api_proto_playlist_proto_depIdxs,
		MessageInfos:      file_api_proto_playlist_proto_msgTypes,
	}.Build()
	File_api_proto_playlist_proto = out.File
	file_api_proto_playlist_proto_rawDesc = nil
	file_api_proto_playlist_proto_goTypes = nil
	file_api_proto_playlist_proto_depIdxs = nil
}
